[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.19.1" }
env_logger = "0.10"
serde = "1.0"
plotters = "0.3.5"
bincode = "1.3.3"
trajectory-core = { path = "../core" }